platform :ios, '9.0'

target 'YDMediator_Example' do
  pod 'YDMediator', :path => '../'

  target 'YDMediator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
