use_frameworks!

platform :ios, '9.0'

target 'YDMediator_Example' do
  pod 'YDMediator', :path => '../'

  target 'YDMediator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
